"""Update tables

Revision ID: 6bac083f77e8
Revises: 5ced6ce0e89f
Create Date: 2023-08-09 01:51:46.507491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bac083f77e8'
down_revision = '5ced6ce0e89f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_result', 'season_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'player', ['name'])
    op.alter_column('player_match_result', 'match_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_match_result', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_match_result', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_match_result', 'match_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'player', type_='unique')
    op.alter_column('match_result', 'season_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
